{
 "title": "Power monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "query0" }
  ]
 },
 "panels": [
  {
   "title": "Power usage vs generation",
   "type": "timeseries",
   "description": "Power usage",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "expr": "ac_output_active_power{instance=\"anern_monitoring:8081\"} / 60 / 1000",
     "legendFormat": "Power consumption (kWh)"
    },
    {
     "expr": "pv_power{instance=\"anern_monitoring:8081\"}  / 60 / 1000",
     "legendFormat": "Power generation (PV)"
    }
   ]
  },
  {
   "title": "Power consumption vs generation",
   "type": "timeseries",
   "description": "Power consumption vs generation",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "ac_output_active_power{instance=\"anern_monitoring:8081\"}",
     "legendFormat": "Power consumption"
    },
    {
     "expr": "pv_power{instance=\"anern_monitoring:8081\"}",
     "legendFormat": "PV Power generation"
    }
   ]
  },
  {
   "title": "Battery capacity",
   "type": "timeseries",
   "description": "Battery capacity",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "battery_percent{instance=\"anern_monitoring:8081\"}",
     "legendFormat": "Battery capacity"
    }
   ]
  },
  {
   "title": "Grid voltage",
   "type": "timeseries",
   "description": "Grid voltage",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "grid_voltage{instance=\"anern_monitoring:8081\"}",
     "legendFormat": "Grid voltage"
    }
   ]
  }
 ]
}